# Change prefix from Ctrl+b to Ctrl + x
set -g prefix C-x
unbind-key C-b
bind-key C-x send-prefix 

set -gq allow-passthrough on
set -g visual-activity off

set -g detach-on-destroy off

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option remain-on-exit on

bind-key -r n next-window
bind-key -r p previous-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'gunawanahmad/tmux-simple'
set -g @plugin 'tmux-plugins/tmux-yank'

bind-key f run-shell "tmux neww ~/dotfiles/script/script/tmux-sessionizer"

# Enable mouse mode
set -g mouse on
bind 'v' copy-mode

# Setup 'v' to begin selection, just like Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Update the default binding of 'Enter' to use copy-selection-and-cancel
unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

# Reduce delay when pressing Escape in Vim
# set -sg escape-time 10

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
