#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/code/porn ~/code/work/ ~/dotfiles/nvim/.config/ ~/Documents/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ $selected_name == "padelva-service" ]]; then
    tmux rename-window -t $selected_name:0 "Neovim"
    tmux new-window -t $selected_name:1 -n "Command center" -c "$selected/apps/command-center" -d
    tmux new-window -t $selected_name:2 -n "chico" -c "$selected/apps/chico" -d
    tmux new-window -t $selected_name:3 -n "streaming-worker" -c "$selected/apps/streaming-worker" -d
elif [[ $selected_name == "padelva-frontend" ]]; then
    tmux rename-window -t $selected_name:0 "Neovim"
    tmux new-window -t $selected_name:1 -n "pnpm" -c "$selected/apps/frontend" -d
fi

tmux switch-client -t $selected_name
